FROM quay.io/toolbx-images/debian-toolbox:unstable

LABEL com.github.containers.toolbox="true" \
    usage="This image is meant to be used with the toolbox or distrobox command" \
    summary="A small image containing common needed tools. Debian edition."

ENV DEBIAN_FRONTEND=noninteractive

COPY distrobox-packages /
RUN apt-get update && \
    apt-get install -y $(apt-cache show $(cat /distrobox-packages) 2> /dev/null | grep "Package:" | sort -u | cut -d' ' -f2-) && \
    rm /distrobox-packages

COPY extra-packages /
RUN apt-get update && \
    grep -v '^#' /extra-packages | xargs apt-get -y install && \
    rm /extra-packages

RUN sed -i "s|#.*en_US.UTF-8|en_US.UTF-8|g" /etc/locale.gen && \
    sed -i "s|#.*de_DE.UTF-8|de_DE.UTF-8|g" /etc/locale.gen
RUN locale-gen && \
    dpkg-reconfigure locales

COPY files/Brewfile /etc/Brewfile

RUN mkdir -p /usr/share/fish/vendor_conf.d/
COPY files/conf/*.fish /usr/share/fish/vendor_conf.d/

RUN mkdir -p /usr/share/fish/vendor_functions.d/
COPY files/func/*.fish /usr/share/fish/vendor_functions.d/
